---
version: '2'
services:
  common:
    build: "."
    environment:
      NODE_ENV: production
  app:
    extends:
      service: common
    ports:
    - 80:80
    command: "/usr/sbin/apache2ctl -D FOREGROUND"

